<?xml version="1.0" encoding="utf-8"?><Database Name="NegoShoe" Class="NegoshoeDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=PEDHGA137\SQL2012;Initial Catalog=NegoShoe;Integrated Security=True" SettingsObjectName="NegoShoeTracker.Library.Properties.Settings" SettingsPropertyName="NegoShoeConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ItemStatus" Member="ItemStatus">
    <Type Name="ItemStatus">
      <Column Name="RecordID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ShipmentItem" Member="ShipmentItems">
    <Type Name="ShipmentItem">
      <Column Name="RecordID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ItemName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="MerchantID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BoughtPrice" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="TargetPrice" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="SoldPrice" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="StatusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CurrentExchangeRate" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Merchant" Member="Merchants">
    <Type Name="Merchant">
      <Column Name="MerchantID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="URL" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Purchase" Member="Purchases">
    <Type Name="Purchase">
      <Column Name="PurchaseID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MerchantID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TotalInUSD" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TotalInPeso" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ExchangeRate" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PurchaseDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Remarks" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PurchaseItem" Member="PurchaseItems">
    <Type Name="PurchaseItem">
      <Column Name="PurchaseItemID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PurchaseID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ItemName" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BoughtPrice" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="TargetPrice" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="SoldPrice" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="StatusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Remarks" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ReservationItem" Member="ReservationItems">
    <Type Name="ReservationItem">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ItemName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="QuantityOrdered" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RemainingUnreserved" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Reserver" Member="Reservers">
    <Type Name="Reserver">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="QuantityReserved" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ItemID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Shipment" Member="Shipments">
    <Type Name="Shipment">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ShipmentNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ShipmentName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ArrivalDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SalexTax" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ShippingCost" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ShoppingCharge" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Profit" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="CurrentExchangeRate" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Notes" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TotalCost" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="TotalProjectedSales" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="TotalSales" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="SubTotal" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>